//  "$NAME" "functional"
// Generated by async_functional_gen

module $NAME (y, $INPUT_LIST, vdd, vss);

  input vdd, vss; 

  input $INPUT_LIST;

  output y;

wire int1, pu, pd, _y; 

assign pu = $PULL_UP_COND;
assign pd = $PULL_DOWN_COND; 

assign int1 = pd ?  1'b0 : (pu ? 1'b1 : 1'bz);

not (strong1, strong0) u1 (_y, int1); 
not (weak1, weak0) u2 (int1, _y);
not(y,_y);

specify
	specparam trise_pu = (0.22:0.22:0.22);
	specparam tfall_pu = (0.25:0.25:0.25);

	specparam trise_pd = (0.22:0.22:0.22);
	specparam tfall_pd = (0.25:0.25:0.25);

	if(pu) ($PULL_UP_LIST *> y) = (trise_pu, tfall_pu);
	if(pd) ($PULL_DOWN_LIST *> y) = (trise_pd, tfall_pd); 
endspecify  

endmodule