// "KEEPB_X1" "functional"


module KEEPB_X2 ( y, a, vdd, vss );

  inout a;
  input vdd,vss;
  output y;

  not (strong1, strong0) i1 (y, a); 
  not (weak1, weak0) i2 (a, y);

  specify
	specparam trise = (0.02:0.02:0.02);
	specparam tfall = (0.02:0.02:0.02);
	(a => y) = (trise, tfall);
  endspecify  

endmodule  
  
// "KEEPB_X1" "functional"


module KEEPB_X4 ( y, a, vdd, vss );

  inout a;
  input vdd,vss;
  output y;

  not (strong1, strong0) i1 (y, a); 
  not (weak1, weak0) i2 (a, y);

  specify
	specparam trise = (0.02:0.02:0.02);
	specparam tfall = (0.02:0.02:0.02);
	(a => y) = (trise, tfall);
  endspecify  

endmodule  
  
//   "A_2C2N2N_RB_X1" "functional"
// Generated by async_functional_gen

module A_2C2N2N_RB_X1 (y,c1,c2,na1,na2,nb1,nb2, pr_B, sr_B, vdd, vss);

  input vdd, vss;
  input pr_B, sr_B;

  input c1,c2,na1,na2,nb1,nb2;

  output y;

wire int1, pu, pd; 

assign pu = ((~c1 & ~c2)) | ~pr_B;
assign pd = ((c1 & c2) & ((na1 & na2)|(nb1 & nb2))) & sr_B; 

assign int1 = pd ?  1'b0 : (pu ? 1'b1 : 1'bz);

not (strong1, strong0) u1 (y, int1); 
not (weak1, weak0) u2 (int1, y);

specify
	specparam trise_pu = (0.22:0.22:0.22);
	specparam tfall_pu = (0.25:0.25:0.25);

	specparam trise_pd = (0.22:0.22:0.22);
	specparam tfall_pd = (0.25:0.25:0.25);

	if(pu) (c1,c2, pr_B *> y) = (trise_pu, tfall_pu);
	if(pd) (c1,c2,na1,na2,nb1,nb2, sr_B *> y) = (trise_pd, tfall_pd); 
endspecify  

endmodule  
  
//   "A_4P1N1N_B_X1" "functional"
// Generated by async_functional_gen

module A_4P1N1N_B_X1 (y, p1,p2,p3,p4,na1,nb1, vdd, vss);

  input vdd, vss; 

  input p1,p2,p3,p4,na1,nb1;

  output y;

wire int1, pu, pd; 

assign pu = ((~p1 & ~p2 & ~p3 & ~p4));
assign pd = ((na1)|(nb1)); 

assign int1 = pd ?  1'b0 : (pu ? 1'b1 : 1'bz);

not (strong1, strong0) u1 (y, int1); 
not (weak1, weak0) u2 (int1, y);

specify
	specparam trise_pu = (0.22:0.22:0.22);
	specparam tfall_pu = (0.25:0.25:0.25);

	specparam trise_pd = (0.22:0.22:0.22);
	specparam tfall_pd = (0.25:0.25:0.25);

	if(pu) (p1,p2,p3,p4 *> y) = (trise_pu, tfall_pu);
	if(pd) (na1,nb1 *> y) = (trise_pd, tfall_pd); 
endspecify  

endmodule  
  
//   "A_2C2N2N_RB_X2" "functional"
// Generated by async_functional_gen

module A_2C2N2N_RB_X2 (y,c1,c2,na1,na2,nb1,nb2, pr_B, sr_B, vdd, vss);

  input vdd, vss;
  input pr_B, sr_B;

  input c1,c2,na1,na2,nb1,nb2;

  output y;

wire int1, pu, pd; 

assign pu = ((~c1 & ~c2)) | ~pr_B;
assign pd = ((c1 & c2) & ((na1 & na2)|(nb1 & nb2))) & sr_B; 

assign int1 = pd ?  1'b0 : (pu ? 1'b1 : 1'bz);

not (strong1, strong0) u1 (y, int1); 
not (weak1, weak0) u2 (int1, y);

specify
	specparam trise_pu = (0.22:0.22:0.22);
	specparam tfall_pu = (0.25:0.25:0.25);

	specparam trise_pd = (0.22:0.22:0.22);
	specparam tfall_pd = (0.25:0.25:0.25);

	if(pu) (c1,c2, pr_B *> y) = (trise_pu, tfall_pu);
	if(pd) (c1,c2,na1,na2,nb1,nb2, sr_B *> y) = (trise_pd, tfall_pd); 
endspecify  

endmodule  
  
//   "A_1C2P1N_X1" "functional"
// Generated by async_functional_gen

module A_1C2P1N_X1 (y, c1,p1,p2,n1, vdd, vss);

  input vdd, vss; 

  input c1,p1,p2,n1;

  output y;

wire int1, pu, pd, _y; 

assign pu = (~c1) & ((~p1 & ~p2));
assign pd = (c1) & ((n1)); 

assign int1 = pd ?  1'b0 : (pu ? 1'b1 : 1'bz);

not (strong1, strong0) u1 (_y, int1); 
not (weak1, weak0) u2 (int1, _y);
not(y,_y);

specify
	specparam trise_pu = (0.22:0.22:0.22);
	specparam tfall_pu = (0.25:0.25:0.25);

	specparam trise_pd = (0.22:0.22:0.22);
	specparam tfall_pd = (0.25:0.25:0.25);

	if(pu) (c1,p1,p2 *> y) = (trise_pu, tfall_pu);
	if(pd) (c1,n1 *> y) = (trise_pd, tfall_pd); 
endspecify  

endmodule  
  
//   "A_1C1P_X1" "functional"
// Generated by async_functional_gen

module A_1C1N_X1 (y, c1,n1, vdd, vss);

  input vdd, vss; 

  input c1,n1;

  output y;

wire int1, pu, pd, _y; 

assign pu = (~c1);
assign pd = (c1) &(n1); 

assign int1 = pd ?  1'b0 : (pu ? 1'b1 : 1'bz);

not (strong1, strong0) u1 (_y, int1); 
not (weak1, weak0) u2 (int1, _y);
not(y,_y);

specify
	specparam trise_pu = (0.22:0.22:0.22);
	specparam tfall_pu = (0.25:0.25:0.25);

	specparam trise_pd = (0.22:0.22:0.22);
	specparam tfall_pd = (0.25:0.25:0.25);

	if(pu) (c1 *> y) = (trise_pu, tfall_pu);
	if(pd) (c1,n1 *> y) = (trise_pd, tfall_pd); 
endspecify  

endmodule  
  
//   "A_2C1N_RB_X4" "functional"
// Generated by xp018_cell_lib_async/functional_gen

module A_2C1N_RB_X4 (y, c1,c2,n1,pr_B,sr_B, vdd, vss);

  input vdd, vss; 

  input c1,c2,n1,pr_B,sr_B;

  output y;

wire int1, pu, pd; 

assign pu = ((~c1 & ~c2)) | ~pr_B;
assign pd = ((c1 & c2) & ((n1))) & sr_B; 

assign int1 = pd ?  1'b0 : (pu ? 1'b1 : 1'bz);

not (strong1, strong0) u1 (y, int1); 
not (weak1, weak0) u2 (int1, y);

specify
	specparam trise_pu = (0.22:0.22:0.22);
	specparam tfall_pu = (0.25:0.25:0.25);

	specparam trise_pd = (0.22:0.22:0.22);
	specparam tfall_pd = (0.25:0.25:0.25);

	if(pu) (c1,c2,pr_B *> y) = (trise_pu, tfall_pu);
	if(pd) (c1,c2,n1,sr_B *> y) = (trise_pd, tfall_pd); 
endspecify  

endmodule  
  
//   "A_1C2N_R_X1" "functional"
// Generated by xp018_cell_lib_async/functional_gen

module A_1C2N_R_X1 (y, c1,n1,n2,pr_B,sr_B, vdd, vss);

  input vdd, vss; 

  input c1,n1,n2,pr_B,sr_B;

  output y;

wire int1, pu, pd, _y; 

assign pu = ((~c1)) | ~pr_B;
assign pd = ((c1) & ((n1 & n2))) & sr_B; 

assign int1 = pd ?  1'b0 : (pu ? 1'b1 : 1'bz);

not (strong1, strong0) u1 (_y, int1); 
not (weak1, weak0) u2 (int1, _y);
not(y,_y);

specify
	specparam trise_pu = (0.22:0.22:0.22);
	specparam tfall_pu = (0.25:0.25:0.25);

	specparam trise_pd = (0.22:0.22:0.22);
	specparam tfall_pd = (0.25:0.25:0.25);

	if(pu) (c1,pr_B *> y) = (trise_pu, tfall_pu);
	if(pd) (c1,n1,n2,sr_B *> y) = (trise_pd, tfall_pd); 
endspecify  

endmodule  
  
//   "A_1C2P1N_B_X4" "functional"
// Generated by async_functional_gen

module A_1C2P1N_B_X4 (y, c1,p1,p2,n1, vdd, vss);

  input vdd, vss; 

  input c1,p1,p2,n1;

  output y;

wire int1, pu, pd; 

assign pu = (~c1) & ((~p1 & ~p2));
assign pd = (c1) & ((n1)); 

assign int1 = pd ?  1'b0 : (pu ? 1'b1 : 1'bz);

not (strong1, strong0) u1 (y, int1); 
not (weak1, weak0) u2 (int1, y);

specify
	specparam trise_pu = (0.22:0.22:0.22);
	specparam tfall_pu = (0.25:0.25:0.25);

	specparam trise_pd = (0.22:0.22:0.22);
	specparam tfall_pd = (0.25:0.25:0.25);

	if(pu) (c1,p1,p2 *> y) = (trise_pu, tfall_pu);
	if(pd) (c1,n1 *> y) = (trise_pd, tfall_pd); 
endspecify  

endmodule  
  
//   "A_2C1N_RB_X4" "functional"
// Generated by xp018_cell_lib_async/functional_gen

module A_2C1N_RB_X1 (y, c1,c2,n1,pr_B,sr_B, vdd, vss);

  input vdd, vss; 

  input c1,c2,n1,pr_B,sr_B;

  output y;

wire int1, pu, pd; 

assign pu = ((~c1 & ~c2)) | ~pr_B;
assign pd = ((c1 & c2) & ((n1))) & sr_B; 

assign int1 = pd ?  1'b0 : (pu ? 1'b1 : 1'bz);

not (strong1, strong0) u1 (y, int1); 
not (weak1, weak0) u2 (int1, y);

specify
	specparam trise_pu = (0.22:0.22:0.22);
	specparam tfall_pu = (0.25:0.25:0.25);

	specparam trise_pd = (0.22:0.22:0.22);
	specparam tfall_pd = (0.25:0.25:0.25);

	if(pu) (c1,c2,pr_B *> y) = (trise_pu, tfall_pu);
	if(pd) (c1,c2,n1,sr_B *> y) = (trise_pd, tfall_pd); 
endspecify  

endmodule  
  
//   "A_1C2P1N_B_X2" "functional"
// Generated by async_functional_gen

module A_1C2P1N_B_X2 (y, c1,p1,p2,n1, vdd, vss);

  input vdd, vss; 

  input c1,p1,p2,n1;

  output y;

wire int1, pu, pd; 

assign pu = (~c1) & ((~p1 & ~p2));
assign pd = (c1) & ((n1)); 

assign int1 = pd ?  1'b0 : (pu ? 1'b1 : 1'bz);

not (strong1, strong0) u1 (y, int1); 
not (weak1, weak0) u2 (int1, y);

specify
	specparam trise_pu = (0.22:0.22:0.22);
	specparam tfall_pu = (0.25:0.25:0.25);

	specparam trise_pd = (0.22:0.22:0.22);
	specparam tfall_pd = (0.25:0.25:0.25);

	if(pu) (c1,p1,p2 *> y) = (trise_pu, tfall_pu);
	if(pd) (c1,n1 *> y) = (trise_pd, tfall_pd); 
endspecify  

endmodule  
  
//   "A_2C_R_X1" "functional"
// Generated by async_functional_gen

module A_2C_R_X1 (y,c1,c2, pr_B, sr_B, vdd, vss);

  input vdd, vss;
  input pr_B, sr_B;

  input c1,c2;

  output y;

wire int1, pu, pd, _y; 

assign pu = ((~c1 & ~c2)) | ~pr_B;
assign pd = ((c1 & c2)) & sr_B;

assign int1 = pd ?  1'b0 : (pu ? 1'b1 : 1'bz);

not (strong1, strong0) u1 (_y, int1); 
not (weak1, weak0) u2 (int1, _y);
not(y, _y);

specify
	specparam trise_pu = (0.22:0.22:0.22);
	specparam tfall_pu = (0.25:0.25:0.25);

	specparam trise_pd = (0.22:0.22:0.22);
	specparam tfall_pd = (0.25:0.25:0.25);

	if(pu) (c1,c2, pr_B *> y) = (trise_pu, tfall_pu);
	if(pd) (c1,c2, sr_B *> y) = (trise_pd, tfall_pd); 
endspecify  

endmodule  
  
// "KEEP_X1" "functional"


module KEEP (y, vdd, vss );

  inout y;
  input vdd,vss;
  wire a;

  not (strong1, strong0) i1 (a, y); 
  not (weak1, weak0) i2 (y, a);

  specify
	specparam trise = (0.02:0.02:0.02);
	specparam tfall = (0.02:0.02:0.02);
	(y => y) = (trise, tfall);
  endspecify  

endmodule  
  
//   "A_1C2N_S_X1" "functional"
// Generated by xp018_cell_lib_async/functional_gen

module A_1C2N_S_X1 (y, c1,n1,n2,pr,sr, vdd, vss);

  input vdd, vss; 

  input c1,n1,n2,pr,sr;

  output y;

wire int1, pu, pd, _y; 

assign pu = ((~c1)) & ~sr;
assign pd = ((c1) & ((n1 & n2))) | pr; 

assign int1 = pd ?  1'b0 : (pu ? 1'b1 : 1'bz);

not (strong1, strong0) u1 (_y, int1); 
not (weak1, weak0) u2 (int1, _y);
not(y,_y);

specify
	specparam trise_pu = (0.22:0.22:0.22);
	specparam tfall_pu = (0.25:0.25:0.25);

	specparam trise_pd = (0.22:0.22:0.22);
	specparam tfall_pd = (0.25:0.25:0.25);

	if(pu) (c1,sr *> y) = (trise_pu, tfall_pu);
	if(pd) (c1,n1,n2,pr *> y) = (trise_pd, tfall_pd); 
endspecify  

endmodule  
  
//   "A_1C2N_SB_X2" "functional"
// Generated by xp018_cell_lib_async/functional_gen

module A_1C2N_SB_X2 (y, c1,n1,n2,pr,sr, vdd, vss);

  input vdd, vss; 

  input c1,n1,n2,pr,sr;

  output y;

wire int1, pu, pd; 

assign pu = ((~c1)) & ~sr;
assign pd = ((c1) & ((n1 & n2))) | pr; 

assign int1 = pd ?  1'b0 : (pu ? 1'b1 : 1'bz);

not (strong1, strong0) u1 (y, int1); 
not (weak1, weak0) u2 (int1, y);

specify
	specparam trise_pu = (0.22:0.22:0.22);
	specparam tfall_pu = (0.25:0.25:0.25);

	specparam trise_pd = (0.22:0.22:0.22);
	specparam tfall_pd = (0.25:0.25:0.25);

	if(pu) (c1,sr *> y) = (trise_pu, tfall_pu);
	if(pd) (c1,n1,n2,pr *> y) = (trise_pd, tfall_pd); 
endspecify  

endmodule  
  
//  "stimulus_freq_generator" "functional"


module stimulus_freq_generator ( );

endmodule  
  
//   "A_3C_RB_X4" "functional"
// Generated by async_functional_gen

module A_3C_RB_X4 (y,c1,c2,c3, pr_B, sr_B, vdd, vss);

  input vdd, vss;
  input pr_B, sr_B;

  input c1,c2,c3;

  output y;

wire int1, pu, pd; 

assign pu = ((~c1 & ~c2 & ~c3)) | ~pr_B;
assign pd = ((c1 & c2 & c3)) & sr_B; 

assign int1 = pd ?  1'b0 : (pu ? 1'b1 : 1'bz);

not (strong1, strong0) u1 (y, int1); 
not (weak1, weak0) u2 (int1, y);

specify
	specparam trise_pu = (0.22:0.22:0.22);
	specparam tfall_pu = (0.25:0.25:0.25);

	specparam trise_pd = (0.22:0.22:0.22);
	specparam tfall_pd = (0.25:0.25:0.25);

	if(pu) (c1,c2,c3, pr_B *> y) = (trise_pu, tfall_pu);
	if(pd) (c1,c2,c3, sr_B *> y) = (trise_pd, tfall_pd); 
endspecify  

endmodule  
  
//   "A_4C_RB_X1" "functional"
// Generated by async_functional_gen

module A_4C_RB_X1 (y,c1,c2,c3,c4, pr_B, sr_B, vdd, vss);

  input vdd, vss;
  input pr_B, sr_B;

  input c1,c2,c3,c4;

  output y;

wire int1, pu, pd; 

assign pu = ((~c1 & ~c2 & ~c3 & ~c4)) | ~pr_B;
assign pd = ((c1 & c2 & c3 & c4)) & sr_B; 

assign int1 = pd ?  1'b0 : (pu ? 1'b1 : 1'bz);

not (strong1, strong0) u1 (y, int1); 
not (weak1, weak0) u2 (int1, y);

specify
	specparam trise_pu = (0.22:0.22:0.22);
	specparam tfall_pu = (0.25:0.25:0.25);

	specparam trise_pd = (0.22:0.22:0.22);
	specparam tfall_pd = (0.25:0.25:0.25);

	if(pu) (c1,c2,c3,c4, pr_B *> y) = (trise_pu, tfall_pu);
	if(pd) (c1,c2,c3,c4, sr_B *> y) = (trise_pd, tfall_pd); 
endspecify  

endmodule  
  
//   "A_1C2P1N_B_X1" "functional"
// Generated by async_functional_gen

module A_1C2P1N_B_X1 (y, c1,p1,p2,n1, vdd, vss);

  input vdd, vss; 

  input c1,p1,p2,n1;

  output y;

wire int1, pu, pd; 

assign pu = (~c1) & ((~p1 & ~p2));
assign pd = (c1) & ((n1)); 

assign int1 = pd ?  1'b0 : (pu ? 1'b1 : 1'bz);

not (strong1, strong0) u1 (y, int1); 
not (weak1, weak0) u2 (int1, y);

specify
	specparam trise_pu = (0.22:0.22:0.22);
	specparam tfall_pu = (0.25:0.25:0.25);

	specparam trise_pd = (0.22:0.22:0.22);
	specparam tfall_pd = (0.25:0.25:0.25);

	if(pu) (c1,p1,p2 *> y) = (trise_pu, tfall_pu);
	if(pd) (c1,n1 *> y) = (trise_pd, tfall_pd); 
endspecify  

endmodule  
  
//   "A_1C2N_RB_X1" "functional"
// Generated by xp018_cell_lib_async/functional_gen

module A_1C2N_RB_X1 (y, c1,n1,n2,pr_B,sr_B, vdd, vss);

  input vdd, vss; 

  input c1,n1,n2,pr_B,sr_B;

  output y;

wire int1, pu, pd; 

assign pu = ((~c1)) | ~pr_B;
assign pd = ((c1) & ((n1 & n2))) & sr_B; 

assign int1 = pd ?  1'b0 : (pu ? 1'b1 : 1'bz);

not (strong1, strong0) u1 (y, int1); 
not (weak1, weak0) u2 (int1, y);

specify
	specparam trise_pu = (0.22:0.22:0.22);
	specparam tfall_pu = (0.25:0.25:0.25);

	specparam trise_pd = (0.22:0.22:0.22);
	specparam tfall_pd = (0.25:0.25:0.25);

	if(pu) (c1,pr_B *> y) = (trise_pu, tfall_pu);
	if(pd) (c1,n1,n2,sr_B *> y) = (trise_pd, tfall_pd); 
endspecify  

endmodule  
  
//   "A_1C2N_RB_X2" "functional"
// Generated by xp018_cell_lib_async/functional_gen

module A_1C2N_RB_X2 (y, c1,n1,n2,pr_B,sr_B, vdd, vss);

  input vdd, vss; 

  input c1,n1,n2,pr_B,sr_B;

  output y;

wire int1, pu, pd; 

assign pu = ((~c1)) | ~pr_B;
assign pd = ((c1) & ((n1 & n2))) & sr_B; 

assign int1 = pd ?  1'b0 : (pu ? 1'b1 : 1'bz);

not (strong1, strong0) u1 (y, int1); 
not (weak1, weak0) u2 (int1, y);

specify
	specparam trise_pu = (0.22:0.22:0.22);
	specparam tfall_pu = (0.25:0.25:0.25);

	specparam trise_pd = (0.22:0.22:0.22);
	specparam tfall_pd = (0.25:0.25:0.25);

	if(pu) (c1,pr_B *> y) = (trise_pu, tfall_pu);
	if(pd) (c1,n1,n2,sr_B *> y) = (trise_pd, tfall_pd); 
endspecify  

endmodule  
  
//   "A_2C2N_RB_X4" "functional"
// Generated by async_functional_gen

module A_2C2N_RB_X4 (y,c1,c2,n1,n2, pr_B, sr_B, vdd, vss);

  input vdd, vss;
  input pr_B, sr_B;

  input c1,c2,n1,n2;

  output y;

wire int1, pu, pd; 

assign pu = ((~c1 & ~c2)) | ~pr_B;
assign pd = ((c1 & c2) & ((n1 & n2))) & sr_B; 

assign int1 = pd ?  1'b0 : (pu ? 1'b1 : 1'bz);

not (strong1, strong0) u1 (y, int1); 
not (weak1, weak0) u2 (int1, y);

specify
	specparam trise_pu = (0.22:0.22:0.22);
	specparam tfall_pu = (0.25:0.25:0.25);

	specparam trise_pd = (0.22:0.22:0.22);
	specparam tfall_pd = (0.25:0.25:0.25);

	if(pu) (c1,c2, pr_B *> y) = (trise_pu, tfall_pu);
	if(pd) (c1,c2,n1,n2, sr_B *> y) = (trise_pd, tfall_pd); 
endspecify  

endmodule  
  
//   "A_3C_RB_X1" "functional"
// Generated by async_functional_gen

module A_3C_RB_X1 (y,c1,c2,c3, pr_B, sr_B, vdd, vss);

  input vdd, vss;
  input pr_B, sr_B;

  input c1,c2,c3;

  output y;

wire int1, pu, pd; 

assign pu = ((~c1 & ~c2 & ~c3)) | ~pr_B;
assign pd = ((c1 & c2 & c3)) & sr_B; 

assign int1 = pd ?  1'b0 : (pu ? 1'b1 : 1'bz);

not (strong1, strong0) u1 (y, int1); 
not (weak1, weak0) u2 (int1, y);

specify
	specparam trise_pu = (0.22:0.22:0.22);
	specparam tfall_pu = (0.25:0.25:0.25);

	specparam trise_pd = (0.22:0.22:0.22);
	specparam tfall_pd = (0.25:0.25:0.25);

	if(pu) (c1,c2,c3, pr_B *> y) = (trise_pu, tfall_pu);
	if(pd) (c1,c2,c3, sr_B *> y) = (trise_pd, tfall_pd); 
endspecify  

endmodule  
  
//   "ARBITER" "functional"

module ARBITER(a, b, c, d, y1, y2, vdd, vss);

  input vdd, vss; 

  input a, b, c, d;
  output reg y1, y2;

   reg [1:0] arb = 2'b00;

  initial begin

        y1 = 0;
        y2 = 0;
  end

        always @ (posedge a) begin
    if (arb[0] == 1) begin
      $display("ERROR: arbiter abitration still in progress, your circuit has hazards");
    end else begin
      wait(arb[1] == 0 && c == 0);
      arb[0] = 1;
      #0.6;
      y1 = 1;
      wait(c == 1 | a == 0 );
      #0.17;
      arb[0] = 0;
      y1 = 0;
    end
  end

  always @ (posedge b) begin
    if (arb[1] == 1) begin
      $display("ERROR: arbiter abitration still in progress, your circuit has hazards");
    end else begin
      wait(arb[0] == 0 && d == 0);
      arb[1] = 1;
      #0.6;
      y2 = 1;
      wait(d == 1 | b == 0);
      #0.17;
      arb[1] = 0;
      y2 = 0;
    end
  end
endmodule  
  
//   "A_4C_R_X1" "functional"
// Generated by async_functional_gen

module A_4C_R_X1 (y,c1,c2,c3,c4, pr_B, sr_B, vdd, vss);

  input vdd, vss;
  input pr_B, sr_B;

  input c1,c2,c3,c4;

  output y;

wire int1, pu, pd, _y; 

assign pu = ((~c1 & ~c2 & ~c3 & ~c4)) | ~pr_B;
assign pd = ((c1 & c2 & c3 & c4)) & sr_B;

assign int1 = pd ?  1'b0 : (pu ? 1'b1 : 1'bz);

not (strong1, strong0) u1 (_y, int1); 
not (weak1, weak0) u2 (int1, _y);
not(y, _y);

specify
	specparam trise_pu = (0.22:0.22:0.22);
	specparam tfall_pu = (0.25:0.25:0.25);

	specparam trise_pd = (0.22:0.22:0.22);
	specparam tfall_pd = (0.25:0.25:0.25);

	if(pu) (c1,c2,c3,c4, pr_B *> y) = (trise_pu, tfall_pu);
	if(pd) (c1,c2,c3,c4, sr_B *> y) = (trise_pd, tfall_pd); 
endspecify  

endmodule  
  
//   "A_1C2N_SB_X1" "functional"
// Generated by xp018_cell_lib_async/functional_gen

module A_1C2N_SB_X1 (y, c1,n1,n2,pr,sr, vdd, vss);

  input vdd, vss; 

  input c1,n1,n2,pr,sr;

  output y;

wire int1, pu, pd; 

assign pu = ((~c1)) & ~sr;
assign pd = ((c1) & ((n1 & n2))) | pr; 

assign int1 = pd ?  1'b0 : (pu ? 1'b1 : 1'bz);

not (strong1, strong0) u1 (y, int1); 
not (weak1, weak0) u2 (int1, y);

specify
	specparam trise_pu = (0.22:0.22:0.22);
	specparam tfall_pu = (0.25:0.25:0.25);

	specparam trise_pd = (0.22:0.22:0.22);
	specparam tfall_pd = (0.25:0.25:0.25);

	if(pu) (c1,sr *> y) = (trise_pu, tfall_pu);
	if(pd) (c1,n1,n2,pr *> y) = (trise_pd, tfall_pd); 
endspecify  

endmodule  
  
//   "A_1C3P2P2N_R_X1" "functional"
// Generated by async_functional_gen

module A_1C3P2P2N_R_X1 (y,c1,pa1,pa2,pa3,pb1,pb2,n1,n2, pr_B, sr_B, vdd, vss);

  input vdd, vss;
  input pr_B, sr_B;

  input c1,pa1,pa2,pa3,pb1,pb2,n1,n2;

  output y;

wire int1, pu, pd, _y; 

assign pu = ((~c1) & ((~pa1 & ~pa2 & ~pa3)|(~pb1 & ~pb2))) | ~pr_B;
assign pd = ((c1) & ((n1 & n2))) & sr_B;

assign int1 = pd ?  1'b0 : (pu ? 1'b1 : 1'bz);

not (strong1, strong0) u1 (_y, int1); 
not (weak1, weak0) u2 (int1, _y);
not(y, _y);

specify
	specparam trise_pu = (0.22:0.22:0.22);
	specparam tfall_pu = (0.25:0.25:0.25);

	specparam trise_pd = (0.22:0.22:0.22);
	specparam tfall_pd = (0.25:0.25:0.25);

	if(pu) (c1,pa1,pa2,pa3,pb1,pb2, pr_B *> y) = (trise_pu, tfall_pu);
	if(pd) (c1,n1,n2, sr_B *> y) = (trise_pd, tfall_pd); 
endspecify  

endmodule  
  
//  "A_2N_U_X4" "functional"


module A_2N_U_X4 ( y, n1, n2, vss, vdd);

  input n2;
  input n1;
  inout y;
  input vss;
  input vdd;


	wire pd; 

	assign pd = (n1 & n2);

	assign y = pd ?  1'b0 : 1'bz;


	specify
		specparam trise_pd = (0.22:0.22:0.22);
		specparam tfall_pd = (0.25:0.25:0.25);

		(n1,n2 *> y) = (trise_pd, tfall_pd); 

	endspecify  


endmodule  
  
//  "A_2P_U_X4" "functional"


module A_3P_U_X4 ( y, p1, p2, p3, vdd, vss);

  input p3;
  input p2;
  input p1;
  inout y;
  input vdd;
  input vss;


	wire pu; 

	assign pu = (~p1 & ~p2 & ~p3);

	assign y = pu ?  1'b1 : 1'bz;


	specify
		specparam trise_pu = (0.22:0.22:0.22);
		specparam tfall_pu = (0.25:0.25:0.25);

		(p1,p2,p3 *> y) = (trise_pu, tfall_pu); 

	endspecify  


endmodule  
  
//   "A_2C_X1" "functional"
// Generated by async_functional_gen

module A_2C_X1 (y, c1,c2, vdd, vss);

  input vdd, vss; 

  input c1,c2;

  output y;

wire int1, pu, pd, _y; 

assign pu = (~c1 & ~c2);
assign pd = (c1 & c2); 

assign int1 = pd ?  1'b0 : (pu ? 1'b1 : 1'bz);

not (strong1, strong0) u1 (_y, int1); 
not (weak1, weak0) u2 (int1, _y);
not(y,_y);

specify
	specparam trise_pu = (0.22:0.22:0.22);
	specparam tfall_pu = (0.25:0.25:0.25);

	specparam trise_pd = (0.22:0.22:0.22);
	specparam tfall_pd = (0.25:0.25:0.25);

	if(pu) (c1,c2 *> y) = (trise_pu, tfall_pu);
	if(pd) (c1,c2 *> y) = (trise_pd, tfall_pd); 
endspecify  

endmodule  
  
//  "A_2P_U_X4" "functional"


module A_1P_U_X4 ( y, p1, vdd, vss);

  input p1;
  inout y;
  input vdd;
  input vss;


	wire pu; 

	assign pu = (~p1);

	assign y = pu ?  1'b1 : 1'bz;


	specify
		specparam trise_pu = (0.22:0.22:0.22);
		specparam tfall_pu = (0.25:0.25:0.25);

		(p1 *> y) = (trise_pu, tfall_pu); 

	endspecify  


endmodule  
  
//  "A_2P_U_X4" "functional"


module A_2P_U_X4 ( y, p1, p2, vdd, vss);

  input p2;
  input p1;
  inout y;
  input vdd;
  input vss;


	wire pu; 

	assign pu = (~p1 & ~p2);

	assign y = pu ?  1'b1 : 1'bz;


	specify
		specparam trise_pu = (0.22:0.22:0.22);
		specparam tfall_pu = (0.25:0.25:0.25);

		(p1,p2 *> y) = (trise_pu, tfall_pu); 

	endspecify  


endmodule  
  
//   "A_4C_RB_X4" "functional"
// Generated by async_functional_gen

module A_4C_RB_X4 (y,c1,c2,c3,c4, pr_B, sr_B, vdd, vss);

  input vdd, vss;
  input pr_B, sr_B;

  input c1,c2,c3,c4;

  output y;

wire int1, pu, pd; 

assign pu = ((~c1 & ~c2 & ~c3 & ~c4)) | ~pr_B;
assign pd = ((c1 & c2 & c3 & c4)) & sr_B; 

assign int1 = pd ?  1'b0 : (pu ? 1'b1 : 1'bz);

not (strong1, strong0) u1 (y, int1); 
not (weak1, weak0) u2 (int1, y);

specify
	specparam trise_pu = (0.22:0.22:0.22);
	specparam tfall_pu = (0.25:0.25:0.25);

	specparam trise_pd = (0.22:0.22:0.22);
	specparam tfall_pd = (0.25:0.25:0.25);

	if(pu) (c1,c2,c3,c4, pr_B *> y) = (trise_pu, tfall_pu);
	if(pd) (c1,c2,c3,c4, sr_B *> y) = (trise_pd, tfall_pd); 
endspecify  

endmodule  
  
//   "A_1C2P_B_X1" "functional"
// Generated by async_functional_gen

module A_1C2P_B_X1 (y, c1,p1,p2, vdd, vss);

  input vdd, vss; 

  input c1,p1,p2;

  output y;

wire int1, pu, pd; 

assign pu = (~c1) & ((~p1 & ~p2));
assign pd = (c1); 

assign int1 = pd ?  1'b0 : (pu ? 1'b1 : 1'bz);

not (strong1, strong0) u1 (y, int1); 
not (weak1, weak0) u2 (int1, y);

specify
	specparam trise_pu = (0.22:0.22:0.22);
	specparam tfall_pu = (0.25:0.25:0.25);

	specparam trise_pd = (0.22:0.22:0.22);
	specparam tfall_pd = (0.25:0.25:0.25);

	if(pu) (c1,p1,p2 *> y) = (trise_pu, tfall_pu);
	if(pd) (c1 *> y) = (trise_pd, tfall_pd); 
endspecify  

endmodule  
  
//   "A_2C2N_RB_X1" "functional"
// Generated by async_functional_gen

module A_2C2N_RB_X1 (y,c1,c2,n1,n2, pr_B, sr_B, vdd, vss);

  input vdd, vss;
  input pr_B, sr_B;

  input c1,c2,n1,n2;

  output y;
endmodule  
  
//  "A_2N_U_X4" "functional"


module A_1N_U_X4 ( y, n1, vss, vdd);

  input n1;
  inout y;
  input vss;
  input vdd;


	wire pd; 

	assign pd = (n1);

	assign y = pd ?  1'b0 : 1'bz;


	specify
		specparam trise_pd = (0.22:0.22:0.22);
		specparam tfall_pd = (0.25:0.25:0.25);

		(n1 *> y) = (trise_pd, tfall_pd); 

	endspecify  


endmodule  
  
// "KEEPB_X1" "functional"


module KEEPB_X1 ( y, a, vdd, vss );

  inout a;
  input vdd,vss;
  output y;

  not (strong1, strong0) i1 (y, a); 
  not (weak1, weak0) i2 (a, y);

  specify
	specparam trise = (0.02:0.02:0.02);
	specparam tfall = (0.02:0.02:0.02);
	(a => y) = (trise, tfall);
  endspecify  

endmodule  
  
//   "A_2C_RB_X2" "functional"
// Generated by async_functional_gen

module A_2C_RB_X2 (y,c1,c2, pr_B, sr_B, vdd, vss);

  input vdd, vss;
  input pr_B, sr_B;

  input c1,c2;

  output y;

wire int1, pu, pd; 

assign pu = ((~c1 & ~c2)) | ~pr_B;
assign pd = ((c1 & c2)) & sr_B; 

assign int1 = pd ?  1'b0 : (pu ? 1'b1 : 1'bz);

not (strong1, strong0) u1 (y, int1); 
not (weak1, weak0) u2 (int1, y);

specify
	specparam trise_pu = (0.22:0.22:0.22);
	specparam tfall_pu = (0.25:0.25:0.25);

	specparam trise_pd = (0.22:0.22:0.22);
	specparam tfall_pd = (0.25:0.25:0.25);

	if(pu) (c1,c2, pr_B *> y) = (trise_pu, tfall_pu);
	if(pd) (c1,c2, sr_B *> y) = (trise_pd, tfall_pd); 
endspecify  

endmodule  
  
//   "A_3C_X1" "functional"
// Generated by async_functional_gen

module A_3C_X1 (y, c1,c2,c3, vdd, vss);

  input vdd, vss; 

  input c1,c2,c3;

  output y;

wire int1, pu, pd, _y; 

assign pu = (~c1 & ~c2 & ~c3);
assign pd = (c1 & c2 & c3); 

assign int1 = pd ?  1'b0 : (pu ? 1'b1 : 1'bz);

not (strong1, strong0) u1 (_y, int1); 
not (weak1, weak0) u2 (int1, _y);
not(y,_y);

specify
	specparam trise_pu = (0.22:0.22:0.22);
	specparam tfall_pu = (0.25:0.25:0.25);

	specparam trise_pd = (0.22:0.22:0.22);
	specparam tfall_pd = (0.25:0.25:0.25);

	if(pu) (c1,c2,c3 *> y) = (trise_pu, tfall_pu);
	if(pd) (c1,c2,c3 *> y) = (trise_pd, tfall_pd); 
endspecify  

endmodule  
  
//   "A_4C_RB_X2" "functional"
// Generated by async_functional_gen

module A_4C_RB_X2 (y,c1,c2,c3,c4, pr_B, sr_B, vdd, vss);

  input vdd, vss;
  input pr_B, sr_B;

  input c1,c2,c3,c4;

  output y;

wire int1, pu, pd; 

assign pu = ((~c1 & ~c2 & ~c3 & ~c4)) | ~pr_B;
assign pd = ((c1 & c2 & c3 & c4)) & sr_B; 

assign int1 = pd ?  1'b0 : (pu ? 1'b1 : 1'bz);

not (strong1, strong0) u1 (y, int1); 
not (weak1, weak0) u2 (int1, y);

specify
	specparam trise_pu = (0.22:0.22:0.22);
	specparam tfall_pu = (0.25:0.25:0.25);

	specparam trise_pd = (0.22:0.22:0.22);
	specparam tfall_pd = (0.25:0.25:0.25);

	if(pu) (c1,c2,c3,c4, pr_B *> y) = (trise_pu, tfall_pu);
	if(pd) (c1,c2,c3,c4, sr_B *> y) = (trise_pd, tfall_pd); 
endspecify  

endmodule

//   "A_1C2P_X1" "functional"
// Generated by async_functional_gen

module A_1C2P_X1 (y, c1,p1,p2, vdd, vss);

  input vdd, vss; 

  input c1,p1,p2;

  output y;

wire int1, pu, pd, _y; 

assign pu = (~c1) & ((~p1 & ~p2));
assign pd = (c1); 

assign int1 = pd ?  1'b0 : (pu ? 1'b1 : 1'bz);

not (strong1, strong0) u1 (_y, int1); 
not (weak1, weak0) u2 (int1, _y);
not(y,_y);

specify
	specparam trise_pu = (0.22:0.22:0.22);
	specparam tfall_pu = (0.25:0.25:0.25);

	specparam trise_pd = (0.22:0.22:0.22);
	specparam tfall_pd = (0.25:0.25:0.25);

	if(pu) (c1,p1,p2 *> y) = (trise_pu, tfall_pu);
	if(pd) (c1 *> y) = (trise_pd, tfall_pd); 
endspecify  

endmodule  
  
//   "A_2C_RB_X4" "functional"
// Generated by async_functional_gen

module A_2C_RB_X4 (y,c1,c2, pr_B, sr_B, vdd, vss);

  input vdd, vss;
  input pr_B, sr_B;

  input c1,c2;

  output y;

wire int1, pu, pd; 

assign pu = ((~c1 & ~c2)) | ~pr_B;
assign pd = ((c1 & c2)) & sr_B; 

assign int1 = pd ?  1'b0 : (pu ? 1'b1 : 1'bz);

not (strong1, strong0) u1 (y, int1); 
not (weak1, weak0) u2 (int1, y);

specify
	specparam trise_pu = (0.22:0.22:0.22);
	specparam tfall_pu = (0.25:0.25:0.25);

	specparam trise_pd = (0.22:0.22:0.22);
	specparam tfall_pd = (0.25:0.25:0.25);

	if(pu) (c1,c2, pr_B *> y) = (trise_pu, tfall_pu);
	if(pd) (c1,c2, sr_B *> y) = (trise_pd, tfall_pd); 
endspecify  

endmodule  
  
//   "A_2C2N2N_RB_X4" "functional"
// Generated by async_functional_gen

module A_2C2N2N_RB_X4 (y,c1,c2,na1,na2,nb1,nb2, pr_B, sr_B, vdd, vss);

  input vdd, vss;
  input pr_B, sr_B;

  input c1,c2,na1,na2,nb1,nb2;

  output y;

wire int1, pu, pd; 

assign pu = ((~c1 & ~c2)) | ~pr_B;
assign pd = ((c1 & c2) & ((na1 & na2)|(nb1 & nb2))) & sr_B; 

assign int1 = pd ?  1'b0 : (pu ? 1'b1 : 1'bz);

not (strong1, strong0) u1 (y, int1); 
not (weak1, weak0) u2 (int1, y);

specify
	specparam trise_pu = (0.22:0.22:0.22);
	specparam tfall_pu = (0.25:0.25:0.25);

	specparam trise_pd = (0.22:0.22:0.22);
	specparam tfall_pd = (0.25:0.25:0.25);

	if(pu) (c1,c2, pr_B *> y) = (trise_pu, tfall_pu);
	if(pd) (c1,c2,na1,na2,nb1,nb2, sr_B *> y) = (trise_pd, tfall_pd); 
endspecify  

endmodule  
  
//   "A_3C_R_X1" "functional"
// Generated by async_functional_gen

module A_3C_R_X1 (y,c1,c2,c3, pr_B, sr_B, vdd, vss);

  input vdd, vss;
  input pr_B, sr_B;

  input c1,c2,c3;

  output y;

wire int1, pu, pd, _y; 

assign pu = ((~c1 & ~c2 & ~c3)) | ~pr_B;
assign pd = ((c1 & c2 & c3)) & sr_B;

assign int1 = pd ?  1'b0 : (pu ? 1'b1 : 1'bz);

not (strong1, strong0) u1 (_y, int1); 
not (weak1, weak0) u2 (int1, _y);
not(y, _y);

specify
	specparam trise_pu = (0.22:0.22:0.22);
	specparam tfall_pu = (0.25:0.25:0.25);

	specparam trise_pd = (0.22:0.22:0.22);
	specparam tfall_pd = (0.25:0.25:0.25);

	if(pu) (c1,c2,c3, pr_B *> y) = (trise_pu, tfall_pu);
	if(pd) (c1,c2,c3, sr_B *> y) = (trise_pd, tfall_pd); 
endspecify  

endmodule  
  
//   "A_1C1P_B_X1" "functional"
// Generated by async_functional_gen

module A_1C1P_B_X1 (y, c1,p1, vdd, vss);

  input vdd, vss; 

  input c1,p1;

  output y;

wire int1, pu, pd; 

assign pu = (~c1) & ((~p1));
assign pd = (c1); 

assign int1 = pd ?  1'b0 : (pu ? 1'b1 : 1'bz);

not (strong1, strong0) u1 (y, int1); 
not (weak1, weak0) u2 (int1, y);

specify
	specparam trise_pu = (0.22:0.22:0.22);
	specparam tfall_pu = (0.25:0.25:0.25);

	specparam trise_pd = (0.22:0.22:0.22);
	specparam tfall_pd = (0.25:0.25:0.25);

	if(pu) (c1,p1 *> y) = (trise_pu, tfall_pu);
	if(pd) (c1 *> y) = (trise_pd, tfall_pd); 
endspecify  

endmodule  
  
//   "A_2C2N_R_X1" "functional"
// Generated by async_functional_gen

module A_2C2N_R_X1 (y,c1,c2,n1,n2, pr_B, sr_B, vdd, vss);

  input vdd, vss;
  input pr_B, sr_B;

  input c1,c2,n1,n2;

  output y;

wire int1, pu, pd, _y; 

assign pu = ((~c1 & ~c2)) | ~pr_B;
assign pd = ((c1 & c2) & ((n1 & n2))) & sr_B;

assign int1 = pd ?  1'b0 : (pu ? 1'b1 : 1'bz);

not (strong1, strong0) u1 (_y, int1); 
not (weak1, weak0) u2 (int1, _y);
not(y, _y);

specify
	specparam trise_pu = (0.22:0.22:0.22);
	specparam tfall_pu = (0.25:0.25:0.25);

	specparam trise_pd = (0.22:0.22:0.22);
	specparam tfall_pd = (0.25:0.25:0.25);

	if(pu) (c1,c2, pr_B *> y) = (trise_pu, tfall_pu);
	if(pd) (c1,c2,n1,n2, sr_B *> y) = (trise_pd, tfall_pd); 
endspecify  

endmodule  
  
//   "A_1C2N_RB_X4" "functional"
// Generated by xp018_cell_lib_async/functional_gen

module A_1C2N_RB_X4 (y, c1,n1,n2,pr_B,sr_B, vdd, vss);

  input vdd, vss; 

  input c1,n1,n2,pr_B,sr_B;

  output y;

wire int1, pu, pd; 

assign pu = ((~c1)) | ~pr_B;
assign pd = ((c1) & ((n1 & n2))) & sr_B; 

assign int1 = pd ?  1'b0 : (pu ? 1'b1 : 1'bz);

not (strong1, strong0) u1 (y, int1); 
not (weak1, weak0) u2 (int1, y);

specify
	specparam trise_pu = (0.22:0.22:0.22);
	specparam tfall_pu = (0.25:0.25:0.25);

	specparam trise_pd = (0.22:0.22:0.22);
	specparam tfall_pd = (0.25:0.25:0.25);

	if(pu) (c1,pr_B *> y) = (trise_pu, tfall_pu);
	if(pd) (c1,n1,n2,sr_B *> y) = (trise_pd, tfall_pd); 
endspecify  

endmodule  
  
//   "A_1C2N_SB_X4" "functional"
// Generated by xp018_cell_lib_async/functional_gen

module A_1C2N_SB_X4 (y, c1,n1,n2,pr,sr, vdd, vss);

  input vdd, vss; 

  input c1,n1,n2,pr,sr;

  output y;

wire int1, pu, pd; 

assign pu = ((~c1)) & ~sr;
assign pd = ((c1) & ((n1 & n2))) | pr; 

assign int1 = pd ?  1'b0 : (pu ? 1'b1 : 1'bz);

not (strong1, strong0) u1 (y, int1); 
not (weak1, weak0) u2 (int1, y);

specify
	specparam trise_pu = (0.22:0.22:0.22);
	specparam tfall_pu = (0.25:0.25:0.25);

	specparam trise_pd = (0.22:0.22:0.22);
	specparam tfall_pd = (0.25:0.25:0.25);

	if(pu) (c1,sr *> y) = (trise_pu, tfall_pu);
	if(pd) (c1,n1,n2,pr *> y) = (trise_pd, tfall_pd); 
endspecify  

endmodule  
  
//   "A_2C2N2N_R_X1" "functional"
// Generated by async_functional_gen

module A_2C2N2N_R_X1 (y,c1,c2,na1,na2,nb1,nb2, pr_B, sr_B, vdd, vss);

  input vdd, vss;
  input pr_B, sr_B;

  input c1,c2,na1,na2,nb1,nb2;

  output y;

wire int1, pu, pd, _y; 

assign pu = ((~c1 & ~c2)) | ~pr_B;
assign pd = ((c1 & c2) & ((na1 & na2)|(nb1 & nb2))) & sr_B;

assign int1 = pd ?  1'b0 : (pu ? 1'b1 : 1'bz);

not (strong1, strong0) u1 (_y, int1); 
not (weak1, weak0) u2 (int1, _y);
not(y, _y);

specify
	specparam trise_pu = (0.22:0.22:0.22);
	specparam tfall_pu = (0.25:0.25:0.25);

	specparam trise_pd = (0.22:0.22:0.22);
	specparam tfall_pd = (0.25:0.25:0.25);

	if(pu) (c1,c2, pr_B *> y) = (trise_pu, tfall_pu);
	if(pd) (c1,c2,na1,na2,nb1,nb2, sr_B *> y) = (trise_pd, tfall_pd); 
endspecify  

endmodule  
  
//   "A_2C2P_RB_X1" "functional"
// Generated by async_functional_gen

module A_2C2P_RB_X1 (y,c1,c2,p1,p2, pr_B, sr_B, vdd, vss);

  input vdd, vss;
  input pr_B, sr_B;

  input c1,c2,p1,p2;

  output y;

wire int1, pu, pd; 

assign pu = ((~c1 & ~c2) & ((~p1 & ~p2))) | ~pr_B;
assign pd = ((c1 & c2)) & sr_B; 

assign int1 = pd ?  1'b0 : (pu ? 1'b1 : 1'bz);

not (strong1, strong0) u1 (y, int1); 
not (weak1, weak0) u2 (int1, y);

specify
	specparam trise_pu = (0.22:0.22:0.22);
	specparam tfall_pu = (0.25:0.25:0.25);

	specparam trise_pd = (0.22:0.22:0.22);
	specparam tfall_pd = (0.25:0.25:0.25);

	if(pu) (c1,c2,p1,p2, pr_B *> y) = (trise_pu, tfall_pu);
	if(pd) (c1,c2, sr_B *> y) = (trise_pd, tfall_pd); 
endspecify  

endmodule  
  
//   "A_2C_B_X1" "functional"
// Generated by async_functional_gen

module A_2C_B_X1 (y, c1,c2, vdd, vss);

  input vdd, vss; 

  input c1,c2;

  output y;

wire int1, pu, pd; 

assign pu = (~c1 & ~c2);
assign pd = (c1 & c2); 

assign int1 = pd ?  1'b0 : (pu ? 1'b1 : 1'bz);

not (strong1, strong0) u1 (y, int1); 
not (weak1, weak0) u2 (int1, y);

specify
	specparam trise_pu = (0.22:0.22:0.22);
	specparam tfall_pu = (0.25:0.25:0.25);

	specparam trise_pd = (0.22:0.22:0.22);
	specparam tfall_pd = (0.25:0.25:0.25);

	if(pu) (c1,c2 *> y) = (trise_pu, tfall_pu);
	if(pd) (c1,c2 *> y) = (trise_pd, tfall_pd); 
endspecify  

endmodule  
  
//   "A_1C1P_X1" "functional"
// Generated by async_functional_gen

module A_1C1P_X1 (y, c1,p1, vdd, vss);

  input vdd, vss; 

  input c1,p1;

  output y;

wire int1, pu, pd, _y; 

assign pu = (~c1) & ((~p1));
assign pd = (c1); 

assign int1 = pd ?  1'b0 : (pu ? 1'b1 : 1'bz);

not (strong1, strong0) u1 (_y, int1); 
not (weak1, weak0) u2 (int1, _y);
not(y,_y);

specify
	specparam trise_pu = (0.22:0.22:0.22);
	specparam tfall_pu = (0.25:0.25:0.25);

	specparam trise_pd = (0.22:0.22:0.22);
	specparam tfall_pd = (0.25:0.25:0.25);

	if(pu) (c1,p1 *> y) = (trise_pu, tfall_pu);
	if(pd) (c1 *> y) = (trise_pd, tfall_pd); 
endspecify  

endmodule  
  
//   "A_2C1N_R" "functional"
// Generated by async_functional_gen

module A_2C1N_R_X1 (y,c1,c2,n1, pr_B, sr_B, vdd, vss);

  input vdd, vss;
  input pr_B, sr_B;

  input c1,c2,n1;

  output y;

wire int1, pu, pd, _y; 

assign pu = ((~c1 & ~c2)) | ~pr_B;
assign pd = ((c1 & c2) & ((n1))) & sr_B;

assign int1 = pd ?  1'b0 : (pu ? 1'b1 : 1'bz);

not (strong1, strong0) u1 (_y, int1); 
not (weak1, weak0) u2 (int1, _y);
not(y, _y);

specify
	specparam trise_pu = (0.22:0.22:0.22);
	specparam tfall_pu = (0.25:0.25:0.25);

	specparam trise_pd = (0.22:0.22:0.22);
	specparam tfall_pd = (0.25:0.25:0.25);

	if(pu) (c1,c2, pr_B *> y) = (trise_pu, tfall_pu);
	if(pd) (c1,c2,n1, sr_B *> y) = (trise_pd, tfall_pd); 
endspecify  

endmodule  
  
//   "A_2C2N_RB_X2" "functional"
// Generated by async_functional_gen

module A_2C2N_RB_X2 (y,c1,c2,n1,n2, pr_B, sr_B, vdd, vss);

  input vdd, vss;
  input pr_B, sr_B;

  input c1,c2,n1,n2;

  output y;

wire int1, pu, pd; 

assign pu = ((~c1 & ~c2)) | ~pr_B;
assign pd = ((c1 & c2) & ((n1 & n2))) & sr_B; 

assign int1 = pd ?  1'b0 : (pu ? 1'b1 : 1'bz);

not (strong1, strong0) u1 (y, int1); 
not (weak1, weak0) u2 (int1, y);

specify
	specparam trise_pu = (0.22:0.22:0.22);
	specparam tfall_pu = (0.25:0.25:0.25);

	specparam trise_pd = (0.22:0.22:0.22);
	specparam tfall_pd = (0.25:0.25:0.25);

	if(pu) (c1,c2, pr_B *> y) = (trise_pu, tfall_pu);
	if(pd) (c1,c2,n1,n2, sr_B *> y) = (trise_pd, tfall_pd); 
endspecify  

endmodule  
  
//   "A_3C_B_X1" "functional"
// Generated by async_functional_gen

module A_3C_B_X1 (y, c1,c2,c3, vdd, vss);

  input vdd, vss; 

  input c1,c2,c3;

  output y;

wire int1, pu, pd; 

assign pu = (~c1 & ~c2 & ~c3);
assign pd = (c1 & c2 & c3); 

assign int1 = pd ?  1'b0 : (pu ? 1'b1 : 1'bz);

not (strong1, strong0) u1 (y, int1); 
not (weak1, weak0) u2 (int1, y);

specify
	specparam trise_pu = (0.22:0.22:0.22);
	specparam tfall_pu = (0.25:0.25:0.25);

	specparam trise_pd = (0.22:0.22:0.22);
	specparam tfall_pd = (0.25:0.25:0.25);

	if(pu) (c1,c2,c3 *> y) = (trise_pu, tfall_pu);
	if(pd) (c1,c2,c3 *> y) = (trise_pd, tfall_pd); 
endspecify  

endmodule  
  
//   "A_4P1N1N" "functional"
// Generated by async_functional_gen

module A_4P1N1N (y, p1,p2,p3,p4,na1,nb1, vdd, vss);

  input vdd, vss; 

  input p1,p2,p3,p4,na1,nb1;

  output y;

wire int1, pu, pd, _y; 

assign pu = ((~p1 & ~p2 & ~p3 & ~p4));
assign pd = ((na1)|(nb1)); 

assign int1 = pd ?  1'b0 : (pu ? 1'b1 : 1'bz);

not (strong1, strong0) u1 (_y, int1); 
not (weak1, weak0) u2 (int1, _y);
not(y,_y);

specify
	specparam trise_pu = (0.22:0.22:0.22);
	specparam tfall_pu = (0.25:0.25:0.25);

	specparam trise_pd = (0.22:0.22:0.22);
	specparam tfall_pd = (0.25:0.25:0.25);

	if(pu) (p1,p2,p3,p4 *> y) = (trise_pu, tfall_pu);
	if(pd) (na1,nb1 *> y) = (trise_pd, tfall_pd); 
endspecify  

endmodule  
  
//   "A_4P1N1N_X1" "functional"
// Generated by async_functional_gen

module A_4P1N1N_X1 (y, p1,p2,p3,p4,na1,nb1, vdd, vss);

  input vdd, vss; 

  input p1,p2,p3,p4,na1,nb1;

  output y;

wire int1, pu, pd, _y; 

assign pu = ((~p1 & ~p2 & ~p3 & ~p4));
assign pd = ((na1)|(nb1)); 

assign int1 = pd ?  1'b0 : (pu ? 1'b1 : 1'bz);

not (strong1, strong0) u1 (_y, int1); 
not (weak1, weak0) u2 (int1, _y);
not(y,_y);

specify
	specparam trise_pu = (0.22:0.22:0.22);
	specparam tfall_pu = (0.25:0.25:0.25);

	specparam trise_pd = (0.22:0.22:0.22);
	specparam tfall_pd = (0.25:0.25:0.25);

	if(pu) (p1,p2,p3,p4 *> y) = (trise_pu, tfall_pu);
	if(pd) (na1,nb1 *> y) = (trise_pd, tfall_pd); 
endspecify  

endmodule  
  
//   "A_1C1P2N_R_X1" "functional"
// Generated by async_functional_gen

module A_1C1P2N_R_X1 (y,c1,p1,n1,n2, pr_B, sr_B, vdd, vss);

  input vdd, vss;
  input pr_B, sr_B;

  input c1,p1,n1,n2;

  output y;

wire int1, pu, pd, _y; 

assign pu = ((~c1) & ((~p1))) | ~pr_B;
assign pd = ((c1) & ((n1 & n2))) & sr_B;

assign int1 = pd ?  1'b0 : (pu ? 1'b1 : 1'bz);

not (strong1, strong0) u1 (_y, int1); 
not (weak1, weak0) u2 (int1, _y);
not(y, _y);

specify
	specparam trise_pu = (0.22:0.22:0.22);
	specparam tfall_pu = (0.25:0.25:0.25);

	specparam trise_pd = (0.22:0.22:0.22);
	specparam tfall_pd = (0.25:0.25:0.25);

	if(pu) (c1,p1, pr_B *> y) = (trise_pu, tfall_pu);
	if(pd) (c1,n1,n2, sr_B *> y) = (trise_pd, tfall_pd); 
endspecify  

endmodule  
  
//   "A_2C1N_RB_X4" "functional"
// Generated by xp018_cell_lib_async/functional_gen

module A_2C1P1N_RB_X1 (y, c1,c2,n1, p1 ,pr_B,sr_B, vdd, vss);

  input vdd, vss; 

  input c1,c2,n1, p1,pr_B,sr_B;

  output y;

wire int1, pu, pd; 

assign pu = ((~c1 & ~c2 & ~p1)) | ~pr_B;
assign pd = ((c1 & c2) & ((n1))) & sr_B; 

assign int1 = pd ?  1'b0 : (pu ? 1'b1 : 1'bz);

not (strong1, strong0) u1 (y, int1); 
not (weak1, weak0) u2 (int1, y);

specify
	specparam trise_pu = (0.22:0.22:0.22);
	specparam tfall_pu = (0.25:0.25:0.25);

	specparam trise_pd = (0.22:0.22:0.22);
	specparam tfall_pd = (0.25:0.25:0.25);

	if(pu) (c1,c2,pr_B, p1 *> y) = (trise_pu, tfall_pu);
	if(pd) (c1,c2,n1,sr_B *> y) = (trise_pd, tfall_pd); 
endspecify  

endmodule  
  
//   "A_2C_RB_X1" "functional"
// Generated by async_functional_gen

module A_2C_RB_X1 (y,c1,c2, pr_B, sr_B, vdd, vss);

  input vdd, vss;
  input pr_B, sr_B;

  input c1,c2;

  output y;

wire int1, pu, pd; 

assign pu = ((~c1 & ~c2)) | ~pr_B;
assign pd = ((c1 & c2)) & sr_B; 

assign int1 = pd ?  1'b0 : (pu ? 1'b1 : 1'bz);

not (strong1, strong0) u1 (y, int1); 
not (weak1, weak0) u2 (int1, y);

specify
	specparam trise_pu = (0.22:0.22:0.22);
	specparam tfall_pu = (0.25:0.25:0.25);

	specparam trise_pd = (0.22:0.22:0.22);
	specparam tfall_pd = (0.25:0.25:0.25);

	if(pu) (c1,c2, pr_B *> y) = (trise_pu, tfall_pu);
	if(pd) (c1,c2, sr_B *> y) = (trise_pd, tfall_pd); 
endspecify  

endmodule  
  
//   "A_1C1P2N_RB_X1" "functional"
// Generated by async_functional_gen

module A_1C1P2N_RB_X1 (y,c1,p1,n1,n2, pr_B, sr_B, vdd, vss);

  input vdd, vss;
  input pr_B, sr_B;

  input c1,p1,n1,n2;

  output y;

wire int1, pu, pd; 

assign pu = ((~c1) & ((~p1))) | ~pr_B;
assign pd = ((c1) & ((n1 & n2))) & sr_B; 

assign int1 = pd ?  1'b0 : (pu ? 1'b1 : 1'bz);

not (strong1, strong0) u1 (y, int1); 
not (weak1, weak0) u2 (int1, y);

specify
	specparam trise_pu = (0.22:0.22:0.22);
	specparam tfall_pu = (0.25:0.25:0.25);

	specparam trise_pd = (0.22:0.22:0.22);
	specparam tfall_pd = (0.25:0.25:0.25);

	if(pu) (c1,p1, pr_B *> y) = (trise_pu, tfall_pu);
	if(pd) (c1,n1,n2, sr_B *> y) = (trise_pd, tfall_pd); 
endspecify  

endmodule  
  
//   "A_1C1P_R_X1" "functional"
// Generated by async_functional_gen

module A_1C1P_R_X1 (y,c1,p1, pr_B, sr_B, vdd, vss);

  input vdd, vss;
  input pr_B, sr_B;

  input c1,p1;

  output y;

wire int1, pu, pd, _y; 

assign pu = ((~c1) & ((~p1))) | ~pr_B;
assign pd = ((c1)) & sr_B;

assign int1 = pd ?  1'b0 : (pu ? 1'b1 : 1'bz);

not (strong1, strong0) u1 (_y, int1); 
not (weak1, weak0) u2 (int1, _y);
not(y, _y);

specify
	specparam trise_pu = (0.22:0.22:0.22);
	specparam tfall_pu = (0.25:0.25:0.25);

	specparam trise_pd = (0.22:0.22:0.22);
	specparam tfall_pd = (0.25:0.25:0.25);

	if(pu) (c1,p1, pr_B *> y) = (trise_pu, tfall_pu);
	if(pd) (c1, sr_B *> y) = (trise_pd, tfall_pd); 
endspecify  

endmodule  
  
//   "A_3C_RB_X2" "functional"
// Generated by async_functional_gen

module A_3C_RB_X2 (y,c1,c2,c3, pr_B, sr_B, vdd, vss);

  input vdd, vss;
  input pr_B, sr_B;

  input c1,c2,c3;

  output y;

wire int1, pu, pd; 

assign pu = ((~c1 & ~c2 & ~c3)) | ~pr_B;
assign pd = ((c1 & c2 & c3)) & sr_B; 

assign int1 = pd ?  1'b0 : (pu ? 1'b1 : 1'bz);

not (strong1, strong0) u1 (y, int1); 
not (weak1, weak0) u2 (int1, y);

specify
	specparam trise_pu = (0.22:0.22:0.22);
	specparam tfall_pu = (0.25:0.25:0.25);

	specparam trise_pd = (0.22:0.22:0.22);
	specparam tfall_pd = (0.25:0.25:0.25);

	if(pu) (c1,c2,c3, pr_B *> y) = (trise_pu, tfall_pu);
	if(pd) (c1,c2,c3, sr_B *> y) = (trise_pd, tfall_pd); 
endspecify  

endmodule